version: "3.8"

services:
  mongo_blackjack:
    image: mongo:6
    container_name: mongo_blackjack
    ports:
      - "27017:27017"
    networks:
      - blackjack-net

  postgres_blackjack:
    image: postgres:16
    container_name: postgres_blackjack
    environment:
      POSTGRES_DB: blackjack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - blackjack-net
    volumes:
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always
    command: ["postgres", "-c", "listen_addresses=*"]


  blackjack-api:
    image: blackjack-api:latest
    container_name: blackjack-api
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres_blackjack:5432/blackjack
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=postgres
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_blackjack:27017/blackjack
    depends_on:
      postgres_blackjack:
        condition: service_healthy
      mongo_blackjack:
        condition: service_started
    networks:
      - blackjack-net

networks:
  blackjack-net:
    driver: bridge
    name: blackjack-net

volumes:
  pgdata: