version: "3.8"

services:
  mongo_blackjack:
    image: mongo:6
    container_name: mongo_blackjack
    ports:
      - "27017:27017"
    networks:
      - blackjack-net

  mysql_blackjack:
    image: mysql:8
    container_name: mysql_blackjack
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blackjack
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    restart: always
    networks:
      - blackjack-net

  blackjack-api:
    image: blackjack-api:latest
    container_name: blackjack-api
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      mysql_blackjack:
        condition: service_healthy
      mongo_blackjack:
        condition: service_started
    networks:
      - blackjack-net

networks:
  blackjack-net:
    driver: bridge