version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_blackjack
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blackjack
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:6
    container_name: mongo_blackjack
    restart: always
    ports:
      - "27017:27017"
