server:
  port: 8080

spring:
  application:
    name: blackjack-api
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    pool:
      initial-size: 0
      max-size: 10
      max-idle-time: 30m
      validation-query: "SELECT 1"
      validation-query-timeout: 5s
      max-acquire-time: 10s
      max-create-connection-time: 10s

springdoc:
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springdoc: DEBUG
    io.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG
    reactor.netty: DEBUG