server:
  port: 8080

spring:
  data:
    mongodb:
      host: mongo_blackjack
      port: 27017
      database: blackjack

  r2dbc:
    url: r2dbc:mysql://mysql_blackjack:3306/blackjack
    username: root
    password: root

springdoc:
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springdoc: DEBUG