server:
  port: 8080

spring:
  data:
    mongodb:
      host: mongo_blackjack # Usamos el nombre del servicio
      port: 27017
      database: blackjack

  r2dbc:
    url: r2dbc:mysql://mysql_blackjack:3306/blackjack # Usamos el nombre del servicio
    username: root
    password: root

springdoc:
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springdoc: DEBUG
    io.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG
    reactor.netty: DEBUG